server:
  port: 8088

spring:
  main:
    allow-circular-references: false
  application:
    name: PLAINTE-EN-LIGNE
    domain:
      url: http://localhost:4200
    resources:
      static-locations: classpath:/static/
  datasource:
    password: admin
    username: postgres
    url: jdbc:postgresql://localhost:5432/plaintedb
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      max-lifetime: 30000
      minimum-idle: 5
      connection-timeout: 20000
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: false
  security:
    filterChain:
      filters:
        enabled: jwt
    cors:
      allowed-origins: http://localhost:8088
      allowed-methods: 
        - GET
        - POST 
        - PUT 
        - DELETE
        - OPTIONS
        - PATCH
      allowed-headers: Content-Type, Authorization, Origin, Accept
  mail:
      protocol: smtp
      host: smtp.gmail.com
      port: 587
      username: devstgvap@gmail.com
      password: vbrvlbsmzxaeupqv
      test-connection: false
      properties:
          mail:
              smtp:
                  ssl:
                  trust: smtp.gmail.com
                  auth: true
                  starttls:
                      enable: true

jwt:
  secret: 2bb80d537b1da3e38bd30361aa855686bde0eacd7162fef6a25fe97bf527a25b
  #base64-secret: gy6FjjrA/lco3CQU3+KOyvdYSE4pE5p8qgSRckx+1aQoqAFmTVW7ZKoD7UWeg0WuAFEO7Xq+WEaSb4p/kk6jQg==
  expired-time: 86400


#log app
logging:
  level:
    ROOT: INFO
    bf.plainte.app: 
      - DEBUG
      - INFO
# Pour trace ce qui se passe dans les details près
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
#        orm:
#          jdbc:
#            bind: TRACE