## YAML Template.
---
server:
  port: 8099
  
spring:
  application:
    name: CNSS-PLAINTE-API
    domain:
      url: http://localhost:4200
    resources:
      static-locations: classpath:/static/
  main.allow-circular-references: true
  jpa:
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: update
      jdbc.lob.non_contextual_creation: true
      default_schema: public
  datasource:
    platform: postgres 
    url: jdbc:postgresql://localhost:5432/plaintedb
    username: postgres #testOne 
    password: admin #testOne
  mail:
      protocol: smtp
      host: smtp.gmail.com
      port: 587
      username: devstgvap@gmail.com
      password: vbrvlbsmzxaeupqv
      test-connection: false
      properties:
          mail:
              smtp:
                  ssl:
                  trust: smtp.gmail.com
                  auth: true
                  starttls:
                      enable: true
  data:
    web:
      pageable:
        default-page-size: 100
  springdoc:
    api-docs:
      path: /api-docs
  swagger-ui:
    operationsSorter: method
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    ROOT: INFO
    com.sawdev.cnss.plainte: INFO
    com.sawdev.cnss.plainte.GlobalExceptionHandler: ERROR
    org.springframework.security: DEBUG

app:
  openapi:
    dev-url: http://localhost:8099
    prod-url: https://localhost:8099